ALTER TABLE floors ADD COLUMN IF NOT EXISTS elements JSONB DEFAULT '[]';
ALTER TABLE floors ADD COLUMN IF NOT EXISTS background_url TEXT DEFAULT '';
ALTER TABLE floors ADD COLUMN IF NOT EXISTS background_opacity NUMERIC DEFAULT 0.4;
ALTER TABLE floors ADD COLUMN IF NOT EXISTS layout_template TEXT DEFAULT 'custom';
